ports:
- port: 8000
  onOpen: open-preview
tasks:
- init: >
    python3 -m pip install --upgrade pip setuptools wheel pipenv==2018.11.26 &&
    pipenv install --dev --system --deploy
  command: >
    pytest . --cov=src
github:
    prebuilds:
        pullRequestsFromForks: true
vscode:
  extensions:
    - BazelBuild.vscode-bazel@0.4.0:CNqPe08EnThWfsQXBuinsQ==
