ports:
- port: 8000
  onOpen: open-preview
tasks:
- init: >
    python3 -m pip install --upgrade pip setuptools wheel pipenv==2018.11.26 &&
    pipenv install --dev --system --deploy
  command: >
    make test
github:
    prebuilds:
        pullRequestsFromForks: true
