ports:
- port: 8000
  onOpen: open-preview
tasks:
- init: >
    python3 -m pip install --upgrade pip setuptools wheel pipenv==2018.11.26 &&
    pipenv install --dev --system --deploy
  command: >
    uvicorn src.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
github:
    prebuilds:
        pullRequestsFromForks: true
