version: '3.7'

services:
  web:
    build: .
    command: uvicorn src.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .docker/env
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .docker/env
    ports:
      - 5432:5432

volumes:
  postgres_data: